version: '3.9'
services:
  starter.webapi:
    image: ${DOCKER_REGISTRY-}starterwebapi
    container_name: starterwebapi
    build:
      context: .
      dockerfile: Starter.WebApi/Dockerfile
    ports:
      - 6543:8080
      - 6544:8081

  starter.db:
    image: mxsgrs/starterdb:v1.0.0
    container_name: starterdb
    ports:
      - 1433:1433