version: '3.4'

services:
  starter.webapi:
    image: ${DOCKER_REGISTRY-}starterwebapi
    build:
      context: .
      dockerfile: Starter.WebApi/Dockerfile

  starter.sqlserver:
    image: ${DOCKER_REGISTRY-}starterwebapi
    build:
      context: .
      dockerfile: Starter.WebApi/Dockerfile

  starter.redis:
    image: ${DOCKER_REGISTRY-}starterwebapi
    build:
      context: .
      dockerfile: Starter.WebApi/Dockerfile
