# Register a new user
POST {{HostAddress}}/api/authentication/register
Content-Type: application/json

{
    "EmailAddress": "john.doe@example.com",
    "FirstName": "John",
    "LastName": "Doe",
    "Birthday": "1990-05-15",
    "Gender": "Male",
    "Role": "User",
    "Phone": "123-456-7890"
}

###

# Read an existing user information
GET {{HostAddress}}/api/authentication/profile

###

# Generate access token
POST {{HostAddress}}/api/authentication/generate-token
Content-Type: application/json

{
  "emailAddress": "john.doe@example.com",
  "hashedPassword": "TWF0cml4UmVsb2FkZWQh"
}
