
# Create or update user credentials
POST {{HostAddress}}/UserCredentials/CreateOrUpdate
Content-Type: application/json
Authorization: Bearer {{Jwt}}

{
  "hashedPassword": "TWF0cml4UmVsb2FkZWQh",
  "userRole": "admin"
}

###

# Read user credentials
GET {{HostAddress}}/UserCredentials/Read
Authorization: Bearer {{Jwt}}
