
# Create or update
POST {{HostAddress}}/UserCredentials/CreateOrUpdate
Content-Type: application/json
Authorization: Bearer {{Jwt}}

{
  "firstName": "Jane",
  "lastName": "Doe",
  "emailAddress": "robert.durand@gmail.com"
}

###

# Read
GET {{HostAddress}}/UserCredentials/Read/1
Authorization: Bearer {{Jwt}}

###
